# Borrowed heavily from https://github.com/MyIntervals/emogrifier/blob/master/.github/workflows/ci.yml
name: CI

on:
  - pull_request
  - push

jobs:
  php-lint:
    name: PHP Lint

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 8.0
          - 8.1

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: PHP Lint
        run: find src tests -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l

  composer-validate:
    name: Composer Validate

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.3

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Composer Validate
        run: composer validate --no-check-all --no-check-lock --strict

  static-analysis:
    name: Static Analysis

    runs-on: ubuntu-latest

    needs: [php-lint, composer-validate]

    strategy:
      matrix:
        command:
          - cs-check
        php-version:
          - 7.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run Command
        run: composer ci:${{ matrix.command }}

  unit-tests:
    name: Unit tests

    runs-on: ubuntu-latest

    needs: [php-lint, composer-validate]

    strategy:
      matrix:
        php-version:
          - 8.0
          - 8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: xdebug.max_nesting_level=500

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run Tests
        run: composer ci:tests
